- name: Update sources and upgrade packages
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 9900

- name: enable https for apt
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: Ensure the system can use the HTTPS transport for APT
  stat:
    path: /usr/lib/apt/methods/https

- name: Install packages
  apt:
    state: latest
    update_cache: yes
    name: [
      autoconf,
      automake,
      bison,
      build-essential,
      curl,
      htop,
      libc6-dev,
      libcurl4-openssl-dev,
      libffi-dev,
      libgdbm-dev,
      libreadline6-dev,
      libsqlite3-dev,
      libssl-dev,
      libtool,
      libxml2-dev,
      libxslt-dev,
      libyaml-dev,
      most,
      ncurses-dev,
      openssl,
      pkg-config,
      sqlite3,
      unzip,
      zlib1g,
      zlib1g-dev,
      vim-nox,
      pv,
      xvfb,
      wget,
      iotop,
      ack-grep,
      tmux,
      git,
      socat,
      update-notifier-common,
      makepasswd,
      pbzip2,
      fail2ban,
      whois,
      net-tools,
      debian-keyring,
      debian-archive-keyring
    ]
