- name: Generate locale en_US.UTF-8
  locale_gen: name=en_US.UTF-8 state=present

- name: Generate locale en_CA.UTF-8
  locale_gen: name=en_CA.UTF-8 state=present

- name: Set locale to en_US.UTF-8
  shell: |
    update-locale \
      LANGUAGE='en_US.UTF-8' \
      LANG='en_US.UTF-8' \
      LC_MESSAGES='en_US.UTF-8' \
      LC_ALL='en_US.UTF-8' \
      LC_COLLATE='en_US.UTF-8' \
      LC_CTYPE='en_US.UTF-8'
